# Generated by Django 4.0 on 2022-03-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiabetesPrediction', '0005_delete_user_datalist_gender_datalist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalist',
            name='Gender',
        ),
    ]
