# Generated by Django 4.0 on 2022-03-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiabetesPrediction', '0007_datalist_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='Gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], max_length=1, null=True),
        ),
    ]
