# Generated by Django 4.0 on 2022-03-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiabetesPrediction', '0016_alter_datalist_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalist',
            old_name='Name',
            new_name='FName',
        ),
        migrations.AddField(
            model_name='datalist',
            name='LName',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
