# Generated by Django 4.0 on 2022-04-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiabetesPrediction', '0017_rename_name_datalist_fname_datalist_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='DiabetesPedigreeFunction',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
