# Generated by Django 4.0 on 2022-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiabetesPrediction', '0018_alter_datalist_diabetespedigreefunction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='DiabetesPedigreeFunction',
            field=models.FloatField(),
        ),
    ]
